// @ts-nocheck -- independent review fixtures use intentionally partial dynamic fake clients.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Console111} from '../src/legacy/transport.ts';
import {parseDsl,normalizeDsl,validateGraph} from '../src/legacy/dsl.ts';
import {execute} from '../src/legacy/workbench.ts';
import {digest,snapshot,HIDDEN,redact} from '../src/legacy/util.ts';
const graph=()=>({nodes:[{id:'s',data:{type:'start'}},{id:'e',data:{type:'end'}}],edges:[{id:'s-e',source:'s',target:'e'}]});
const draft=()=>({id:'draft-id',hash:'h1',updated_at:123,graph:graph(),features:{},environment_variables:[{id:'sec',name:'secret',value_type:'secret',value:HIDDEN,description:''},{id:'normal',name:'a',value_type:'string',value:'keep',description:''}],conversation_variables:[{id:'conv',name:'c',value_type:'string',value:'keep',description:''}]});
const dsl=(d:any)=>({kind:'app',version:'0.5.0',app:{mode:'workflow'},workflow:structuredClone(d)});
function sse(events:any[],chunks?:string[]){let parts=chunks??events.map(e=>'data: '+JSON.stringify(e)+'\n\n');return new Response(new ReadableStream({start(c){for(const p of parts)c.enqueue(new TextEncoder().encode(p));c.close()}}),{headers:{'content-type':'text/event-stream'}})}
function transport(events:any[],extra:any={}){return new Console111({baseUrl:'https://example.invalid',cookies:{'__Host-access_token':'TOKEN_SECRET','__Host-csrf_token':'CSRF_SECRET'},fetchImpl:async()=>sse(events),...extra})}
function mockSetup(extra:any={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dify-review-'));const configFile=path.join(dir,'config.json'),stateFile=path.join(dir,'state.json');fs.writeFileSync(configFile,JSON.stringify({profile:'dify-1.11.1',target:{base_url:'https://example.invalid',workspace_id:'workspace',app_id:'app',mode:'workflow'},dsl:'dsl.yml',state_file:'state.json',permissions:{remote:true,sync:true,test:true,publish:true}}));const remote=draft();fs.writeFileSync(path.join(dir,'dsl.yml'),JSON.stringify(dsl(snapshot(remote))));let called:any[]=[];const client={currentWorkspace:async()=>({id:'workspace'}),getApp:async()=>({id:'app',mode:'workflow'}),getDraft:async()=>structuredClone(remote),runDraft:async()=>({status:'succeeded',workflow_run_id:'run-id',task_id:'task-id',events:[]}),getRun:async()=>({id:'run-id',graph:structuredClone(remote.graph),status:'succeeded'}),nodeExecutions:async()=>({data:[]}),stop:async(...a:any[])=>{called.push(a);return{result:'success'}},...extra};return{dir,configFile,stateFile,remote,client,called,cleanup:()=>fs.rmSync(dir,{recursive:true,force:true})}}

test('cookie prefix + CSRF sent without Bearer and redirect disabled',async()=>{let captured:any;const c=transport([],{fetchImpl:async(url:any,init:any)=>{captured={url,init};return new Response('{"id":"app"}',{headers:{'content-type':'application/json'}})}});await c.getApp('app');assert.equal(captured.init.headers['X-CSRF-Token'],'CSRF_SECRET');assert.match(captured.init.headers.Cookie,/__Host-access_token=TOKEN_SECRET/);assert.equal(captured.init.headers.Authorization,undefined);assert.equal(captured.init.redirect,'error')});
test('HTTP public cleartext target rejected',()=>assert.throws(()=>new Console111({baseUrl:'http://example.invalid',cookies:{}}),/HTTPS/));
test('HTML 200 rejected',async()=>{const c=transport([],{fetchImpl:async()=>new Response('<html>login</html>',{headers:{'content-type':'text/html'}})});await assert.rejects(c.getApp('app'),{code:'INVALID_CONTENT_TYPE'})});
test('missing SSE terminal never passes',async()=>assert.equal((await transport([{event:'workflow_started',data:{id:'run'}}]).runDraft('app','workflow',{inputs:{}})).status,'unknown'));
test('partial-succeeded never passes',async()=>assert.equal((await transport([{event:'workflow_finished',data:{id:'run',status:'partial-succeeded'}}]).runDraft('app','workflow',{inputs:{}})).status,'failed'));
test('SSE error cannot be overwritten by success',async()=>{const r=await transport([{event:'error',message:'bad'},{event:'workflow_finished',data:{id:'run',status:'succeeded'}}]).runDraft('app','workflow',{inputs:{}});assert.notEqual(r.status,'succeeded')});
test('split CRLF SSE handles terminal',async()=>{const r=await transport([],{fetchImpl:async()=>sse([],[`data: ${JSON.stringify({event:'workflow_finished',data:{id:'run',status:'succeeded'}})}\r`,'\n\r','\n'])}).runDraft('app','workflow',{inputs:{}});assert.equal(r.status,'succeeded')});
test('omitted env and conv preserve full values',()=>{const r=draft();const n=normalizeDsl(dsl({graph:r.graph,features:r.features}),r,'workflow');assert.deepEqual(n.payload,snapshot(r));assert.equal(digest(n.payload),digest(snapshot(r)))});
test('secret replacement blocked; omitted secret preserved by id',()=>{const r=draft();let d=dsl(snapshot(r));d.workflow.environment_variables[0].value='replacement';assert.throws(()=>normalizeDsl(d,r,'workflow'),{code:'SECRET_CHANGE_BLOCKED'});d.workflow.environment_variables=[];const p=normalizeDsl(d,r,'workflow').payload;assert.deepEqual(p.environment_variables,[r.environment_variables[0]])});
test('encrypted dataset IDs blocked unless explicit UUID mapping',()=>{const r=draft();const d=dsl(snapshot(r));d.workflow.graph.nodes.push({id:'k',data:{type:'knowledge-retrieval',dataset_ids:['encrypted$$']}});assert.throws(()=>normalizeDsl(d,r,'workflow'),{code:'DATASET_BINDING'});assert.deepEqual(normalizeDsl(d,r,'workflow',{'encrypted$$':'12345678-1234-1234-1234-123456789abc'}).datasetIds,['12345678-1234-1234-1234-123456789abc'])});
test('unsupported human input is explicitly blocked',()=>{const g=graph();g.nodes.push({id:'h',data:{type:'human-input'}});assert.throws(()=>validateGraph(g,'workflow'),{code:'UNSUPPORTED_NODE'})});
test('stale baseline conflict never syncs',async()=>{const x=mockSetup();try{await execute('snapshot',{},x);x.remote.hash='changed';await assert.rejects(execute('sync',{expected_digest:digest(snapshot(x.remote))},x),{code:'DRAFT_CONFLICT'})}finally{x.cleanup()}});
test('mismatched workspace aborts before app access',async()=>{let n=0;const x=mockSetup({currentWorkspace:async()=>({id:'other'}),getApp:async()=>{n++;return{id:'app',mode:'workflow'}}});try{await assert.rejects(execute('snapshot',{},x),{code:'WORKSPACE_MISMATCH'});assert.equal(n,0)}finally{x.cleanup()}});
test('arbitrary task cannot be stopped through pinned app',async()=>{const x=mockSetup();try{await assert.rejects(execute('stop',{task_id:'outside-app-task'},x));assert.equal(x.called.length,0)}finally{x.cleanup()}});
test('unknown single-node outcome remains unresolved',async()=>{const x=mockSetup({runNode:async()=>({status:'unknown',task_id:'task-id',workflow_run_id:'run-id',events:[],error:'STREAM_INTERRUPTED'})});try{await execute('snapshot',{},x);await execute('node-run',{node_id:'e',inputs:{},expected_digest:digest(snapshot(x.remote))},x);const state=JSON.parse(fs.readFileSync(x.stateFile,'utf8'));assert.ok(state.pending_mutation)}finally{x.cleanup()}});
test('failed durable run cannot qualify for publishing',async()=>{const x=mockSetup({getRun:async()=>({id:'run-id',workflow_id:'draft-id',status:'failed',error:'bad'})});try{await execute('snapshot',{},x);let result;try{result=await execute('test',{inputs:{},expected_digest:digest(snapshot(x.remote))},x)}catch{}const state=JSON.parse(fs.readFileSync(x.stateFile,'utf8'));assert.notEqual(result?.qualifies_for_publish,true);assert.equal(state.test_receipt,undefined)}finally{x.cleanup()}});

test('network uncertainty never retries mutation',async()=>{let calls=0;const c=transport([],{fetchImpl:async()=>{calls++;throw new Error('secret connection error')}});await assert.rejects(c.syncDraft('app',{hash:'h',graph:{}}),{code:'REQUEST_UNCERTAIN'});assert.equal(calls,1)});
test('publish without successful test receipt makes no remote publish',async()=>{let calls=0;const x=mockSetup({publish:async()=>{calls++;return{result:'success'}}});try{await execute('snapshot',{},x);const hash=digest(snapshot(x.remote));await assert.rejects(execute('publish',{expected_digest:hash,confirm_publish:hash},x),{code:'UNTESTED_DRAFT'});assert.equal(calls,0)}finally{x.cleanup()}});
test('reviewed local digest cannot silently change before sync',async()=>{let calls=0;const x=mockSetup({syncDraft:async()=>{calls++;return{result:'success'}}});try{await execute('snapshot',{},x);const d=dsl(snapshot(x.remote));d.workflow.graph.nodes[1].data.title='changed';fs.writeFileSync(path.join(x.dir,'dsl.yml'),JSON.stringify(d));await assert.rejects(execute('sync',{expected_digest:digest(snapshot(x.remote))},x),{code:'DIGEST_CONFIRMATION_REQUIRED'});assert.equal(calls,0)}finally{x.cleanup()}});
test('code HTTP ifelse and nested iteration graph data preserved',()=>{const r=draft();const g=graph();g.nodes.push({id:'code',data:{type:'code',code:'def main(x): return {"y": x}',code_language:'python3'}},{id:'http',data:{type:'http-request',url:'https://example.invalid/path',authorization:{type:'no-auth'}}},{id:'branch',data:{type:'if-else',cases:[]}},{id:'it',data:{type:'iteration',start_node_id:'is'}},{id:'is',parentId:'it',data:{type:'iteration-start'}});const d=dsl({...snapshot(r),graph:g});const parsed=parseDsl(JSON.stringify(d));const result=normalizeDsl(parsed,r,'workflow');assert.deepEqual(result.payload.graph,g)});
test('build does not execute code stored in DSL',async()=>{const x=mockSetup();try{const marker=path.join(x.dir,'executed');const d=dsl(snapshot(x.remote));d.workflow.graph.nodes.push({id:'code',data:{type:'code',code:`require('fs').writeFileSync(${JSON.stringify(marker)},'bad')`}});fs.writeFileSync(path.join(x.dir,'dsl.yml'),JSON.stringify(d));const r=await execute('build',{},x);assert.equal(r.ok,true);assert.equal(fs.existsSync(marker),false)}finally{x.cleanup()}});
test('configured build command is disabled without explicit permission',async()=>{const x=mockSetup();try{const c=JSON.parse(fs.readFileSync(x.configFile,'utf8'));c.build={command:'node',args:['-e','process.exit(0)']};fs.writeFileSync(x.configFile,JSON.stringify(c));await assert.rejects(execute('build',{},x),{code:'BUILD_DISABLED'})}finally{x.cleanup()}});

import {spawnSync} from 'node:child_process';
test('CLI JSON log errors redact individual session cookie values',()=>{const x=mockSetup();try{const preload=path.join(x.dir,'preload.mjs');fs.writeFileSync(preload,`globalThis.fetch=async(url,init)=>{const p=new URL(url).pathname;let d=p.endsWith('/workspaces/current')?{id:'workspace'}:p.endsWith('/apps/app')?{id:'app',mode:'workflow'}:p.endsWith('/node-executions')?{data:[{id:'n',status:'failed',error:'CSRF_REVIEW_SECRET'}]}:{id:'run-id',status:'failed',error:'log ACCESS_REVIEW_SECRET'};return new Response(JSON.stringify(d),{headers:{'content-type':'application/json'}})};`);const r=spawnSync(process.execPath,['--import',preload,path.resolve('bin/difywf.js'),'logs','--config',x.configFile,'--run-id','run-id'],{encoding:'utf8',env:{...process.env,DIFY_CONSOLE_COOKIE:'access_token=ACCESS_REVIEW_SECRET; csrf_token=CSRF_REVIEW_SECRET'}});assert.equal(r.status,0,r.stderr);assert.doesNotMatch(r.stdout,/ACCESS_REVIEW_SECRET|CSRF_REVIEW_SECRET/)}finally{x.cleanup()}});

test('native DSL selector and numeric types normalize without false diff',()=>{const r=draft();r.environment_variables.push({id:'num',name:'number',value_type:'number',value:2,description:''});const d=dsl(snapshot(r));d.workflow.environment_variables.forEach((v:any)=>v.selector=['env',v.name]);d.workflow.environment_variables.find((v:any)=>v.id==='num').value_type='integer';d.workflow.conversation_variables.forEach((v:any)=>v.selector=['conversation',v.name]);assert.deepEqual(normalizeDsl(d,r,'workflow').payload,snapshot(r))});
test('successful full test qualifies one explicit publish, then receipt consumed',async()=>{let calls=0;const x=mockSetup();x.client.publish=async()=>{calls++;return{result:'success'}};x.client.getPublished=async()=>({...structuredClone(x.remote),id:'published-id'});try{await execute('snapshot',{},x);const expected_digest=digest(snapshot(x.remote));const run=await execute('test',{expected_digest,inputs:{}},x);assert.equal(run.qualifies_for_publish,true);const p=await execute('publish',{expected_digest,confirm_publish:expected_digest},x);assert.equal(p.ok,true);assert.equal(calls,1);await assert.rejects(execute('publish',{expected_digest,confirm_publish:expected_digest},x),{code:'UNTESTED_DRAFT'});assert.equal(calls,1)}finally{x.cleanup()}});
test('uncertain publish stays unresolved and is never automatically retried',async()=>{let calls=0;const x=mockSetup({publish:async()=>{calls++;throw new Error('network failed')}});try{await execute('snapshot',{},x);const expected_digest=digest(snapshot(x.remote));await execute('test',{expected_digest,inputs:{}},x);await assert.rejects(execute('publish',{expected_digest,confirm_publish:expected_digest},x));assert.equal(calls,1);await assert.rejects(execute('publish',{expected_digest,confirm_publish:expected_digest},x),{code:'MUTATION_UNRESOLVED'});assert.equal(calls,1)}finally{x.cleanup()}});
test('known target-bound task can be explicitly stopped after uncertain run',async()=>{const x=mockSetup({runDraft:async()=>({status:'unknown',task_id:'known-task',workflow_run_id:'run-id',events:[],error:'STREAM_INTERRUPTED'})});try{await execute('snapshot',{},x);await execute('test',{expected_digest:digest(snapshot(x.remote)),inputs:{}},x);const r=await execute('stop',{task_id:'known-task'},x);assert.equal(r.ok,true);assert.equal(x.called.length,1);assert.deepEqual(x.called[0],['app','known-task'])}finally{x.cleanup()}});

test('upstream profile environment preserves first CLI argument',()=>{const r=spawnSync(process.execPath,[path.resolve('bin/difywf.js'),'--version'],{encoding:'utf8',env:{...process.env,DIFYWF_PROFILE:'upstream'}});assert.equal(r.status,0);assert.match(r.stdout,/^0\.3\.0\s*$/)});
test('upstream equals-profile after command preserves first CLI argument',()=>{const r=spawnSync(process.execPath,[path.resolve('bin/difywf.js'),'--version','--profile=upstream'],{encoding:'utf8'});assert.equal(r.status,0);assert.match(r.stdout,/^0\.3\.0\s*$/)});
